### PR TITLE
Fix wireguard script internet check

### PR DESCRIPTION
**Pull request by SubhrajyotiSen**

### CODE REVIEW

**Comment by msfjarvis** [comment]
Send these patches to upstream instead, WireGuard users will pull those down once merged.

**Comment by SubhrajyotiSen** [comment]
Thanks. Will do that

**Comment by SubhrajyotiSen** [comment]
The internet check got reverted in upstream xD
https://git.zx2c4.com/android_kernel_wireguard/commit/?id=f63509f99b4052d999be3069abb04d5b63ad55bd

**Comment by msfjarvis** [comment]
> The internet check got reverted in upstream xD
> https://git.zx2c4.com/android_kernel_wireguard/commit/?id=f63509f99b4052d999be3069abb04d5b63ad55bd

Yeah its missing a revert reason but on a fresh clone without internet it'd still break compilation.

**Pull request closed without merging**
